#!/usr/bin/env python3
# Fern-RX888, an RX-888 input module for FernSDR.
# SPDX-License-Identifier: GPL-2.0-or-later
"""Writes a C++ source file that carries text files as C strings, for the
licences --notices prints.

    embed_text.py NAME FILE... [-- NAME FILE...] > notices.cpp

Each NAME becomes a `const char NAME[]` in namespace fern holding its
files, separated by blank lines.
"""
import sys


def literal(text):
    # Adjacent literals of one line each: some compilers limit the length of
    # a single one.
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    lines = escaped.split("\n")
    return ["    \"%s\\n\"" % line for line in lines[:-1]] + ["    \"%s\";" % lines[-1]]


def main():
    groups = [[]]
    for arg in sys.argv[1:]:
        if arg == "--":
            groups.append([])
        else:
            groups[-1].append(arg)
    if any(len(g) < 2 for g in groups):
        sys.exit("usage: embed_text.py NAME FILE... [-- NAME FILE...]")
    out = ["// Generated by tools/embed_text.py; do not edit.", "", "namespace fern {", ""]
    for name, *paths in groups:
        text = "\n\n".join(open(p, encoding="utf-8").read().rstrip() + "\n" for p in paths)
        out.append("extern const char %s[];" % name)
        out.append("const char %s[] =" % name)
        out += literal(text)
        out.append("")
    out += ["}  // namespace fern", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
