#!/usr/bin/env python3
# Fern-RX888, an RX-888 input module for FernSDR.
# SPDX-License-Identifier: GPL-2.0-or-later
"""Writes a C++ source file that carries the FX3 firmware image, its SHA-256
and the licence notices that must travel with it.

    embed_firmware.py IMAGE NOTICE... > firmware_blob.cpp
"""
import hashlib
import sys


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: embed_firmware.py IMAGE NOTICE...")
    image = open(sys.argv[1], "rb").read()
    notices = "\n\n".join(open(p, encoding="utf-8").read().rstrip() + "\n" for p in sys.argv[2:])
    out = ["// Generated by tools/embed_firmware.py from " + sys.argv[1] + "; do not edit.",
           '#include "firmware.h"', "", "namespace fern {", "",
           "const uint8_t embedded_firmware[] = {"]
    for i in range(0, len(image), 16):
        out.append("    " + ", ".join("0x%02x" % b for b in image[i:i + 16]) + ",")
    out.append("};")
    out.append("const size_t embedded_firmware_size = sizeof embedded_firmware;")
    out.append('const char embedded_firmware_sha256[] = "%s";' % hashlib.sha256(image).hexdigest())
    # Raw string literals have a length limit in some compilers; split the
    # notices into adjacent literals of at most 2000 characters.
    out.append("const char embedded_firmware_notices[] =")
    escaped = notices.replace("\\", "\\\\").replace('"', '\\"')
    lines = escaped.split("\n")
    for line in lines[:-1]:
        out.append('    "%s\\n"' % line)
    out.append('    "%s";' % lines[-1])
    out += ["", "}  // namespace fern", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
